exec(open("1. rename png.py").read())
exec(open("2. rename mcmeta.py").read())
exec(open("3. rename json.py").read())
exec(open("4. rename in jsons.py").read())
exec(open("5. edit jsons.py").read())
exec(open("6. rename folders.py").read())
exec(open("7. edit pack.mcmeta.py").read())
exec(open("8. delete cache.py").read())